# Generated by Django 4.2.7 on 2025-11-11 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceEmotionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='voice_samples/')),
                ('detected_emotion', models.CharField(choices=[('angry', 'Angry'), ('calm', 'Calm'), ('fearful', 'Fearful'), ('happy', 'Happy'), ('sad', 'Sad')], max_length=20)),
                ('confidence_score', models.FloatField()),
                ('pitch_mean', models.FloatField(blank=True, null=True)),
                ('pitch_std', models.FloatField(blank=True, null=True)),
                ('energy_mean', models.FloatField(blank=True, null=True)),
                ('speaking_rate', models.FloatField(blank=True, null=True)),
                ('all_predictions', models.JSONField(default=dict)),
                ('audio_duration', models.FloatField(default=0.0)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'voice_emotion_analyses',
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
