# Generated by Django 4.2.7 on 2025-11-11 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacialEmotionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facial_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'facial_emotion_sessions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='FacialEmotionCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_emotion', models.CharField(choices=[('angry', 'Angry'), ('disgust', 'Disgust'), ('fear', 'Fear'), ('happy', 'Happy'), ('neutral', 'Neutral'), ('sad', 'Sad'), ('surprise', 'Surprise')], max_length=20)),
                ('confidence_score', models.FloatField()),
                ('image_snapshot', models.ImageField(blank=True, null=True, upload_to='emotion_captures/')),
                ('face_coordinates', models.JSONField(default=dict)),
                ('all_predictions', models.JSONField(default=dict)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='facial_emotion.facialemotionsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facial_captures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'facial_emotion_captures',
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['-captured_at'], name='facial_emot_capture_61e45c_idx'), models.Index(fields=['user', '-captured_at'], name='facial_emot_user_id_e77a0f_idx')],
            },
        ),
    ]
